{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dboard-simpedes-mui.serviceAccountName" . }}
  labels:
{{ include "dboard-simpedes-mui.labels" . | indent 4 }}
{{- end -}}
